config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'homes#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  get 'docs' => 'homes#docs', as: 'docs'

  get 'users' => 'users#index', as: 'users'
  get 'users/:id' => 'users#show', as: 'mypage'
  get 'group/new' => 'groups#new', as: 'create_group'
  get 'group/:id' => 'groups#show', as: 'group'


  # group
  resources :groups, only: %i[create update edit index]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users

  has_many :payments

  validates :name, presence: true
  validates :description, presence: true
end

app/models/group_user.rb
# frozen_string_literal: true

class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true
  validates :name, presence: true

  has_many :group_users
  has_many :groups, through: :group_users

  has_many :payments, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

class GroupsController < ApplicationController
  def new
    @group = Group.new
  end

  def create
    group = Group.new(group_params)
    group.owner_id = current_user.id
    group.save!
    redirect_to groups_path
  end

  def index
    @groups = Group.all
  end

  def edit; end

  def update; end

  def show
    @group = Group.find(params[:id])
    @group.group_users >> current_user if @group.group_users.include?(current_user)
  end

  private

  def group_params
    params.require(:group).permit(:name, :description, user_ids: [] )
  end
end

app/controllers/homes_controller.rb
# frozen_string_literal: true

class HomesController < ApplicationController
  def top; end

  def docs; end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

module Users
  class ConfirmationsController < Devise::ConfirmationsController
    # GET /resource/confirmation/new
    # def new
    #   super
    # end

    # POST /resource/confirmation
    # def create
    #   super
    # end

    # GET /resource/confirmation?confirmation_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after resending confirmation instructions.
    # def after_resending_confirmation_instructions_path_for(resource_name)
    #   super(resource_name)
    # end

    # The path used after confirmation.
    # def after_confirmation_path_for(resource_name, resource)
    #   super(resource_name, resource)
    # end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    # You should configure your model like this:
    # devise :omniauthable, omniauth_providers: [:twitter]

    # You should also create an action method in this controller like this:
    # def twitter
    # end

    # More info at:
    # https://github.com/heartcombo/devise#omniauth

    # GET|POST /resource/auth/twitter
    # def passthru
    #   super
    # end

    # GET|POST /users/auth/twitter/callback
    # def failure
    #   super
    # end

    # protected

    # The path used when OmniAuth fails
    # def after_omniauth_failure_path_for(scope)
    #   super(scope)
    # end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

module Users
  class PasswordsController < Devise::PasswordsController
    # GET /resource/password/new
    # def new
    #   super
    # end

    # POST /resource/password
    # def create
    #   super
    # end

    # GET /resource/password/edit?reset_password_token=abcdef
    # def edit
    #   super
    # end

    # PUT /resource/password
    # def update
    #   super
    # end

    # protected

    # def after_resetting_password_path_for(resource)
    #   super(resource)
    # end

    # The path used after sending reset password instructions
    # def after_sending_reset_password_instructions_path_for(resource_name)
    #   super(resource_name)
    # end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    # before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_up_params
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    # end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end

    # The path used after sign up.
    def after_sign_up_path_for(_resource)
      mypage_path(current_user.id)
    end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < Devise::SessionsController
    # before_action :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    # def new
    #   super
    # end

    # POST /resource/sign_in
    # def create
    #   super
    # end

    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end

    # action for after sign in
    def after_sign_in_path_for(_resource)
      mypage_path(current_user.id)
    end
    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
    # end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

module Users
  class UnlocksController < Devise::UnlocksController
    # GET /resource/unlock/new
    # def new
    #   super
    # end

    # POST /resource/unlock
    # def create
    #   super
    # end

    # GET /resource/unlock?unlock_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after sending unlock password instructions
    # def after_sending_unlock_instructions_path_for(resource)
    #   super(resource)
    # end

    # The path used after unlocking the resource
    # def after_unlock_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/groups_helper.rb
# frozen_string_literal: true

module GroupsHelper
end

app/helpers/homes_helper.rb
# frozen_string_literal: true

module HomesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/groups/_group_card.html.erb
<div class="p-6 max-w-sm bg-white rounded-lg shadow-md bg-blue-400">
  <span class="material-icons text-white">
    groups
  </span>
  <%= link_to group_path(group.id) do %>
    <h5 class="mb-2 text-2xl text-center font-semibold tracking-tight text-gray-900 dark:text-white">
      <span class='shadow-md shadow-transparent text-ellipsis'><%= group.name %></span>
    </h5>
  <% end %>
  <p class="w-full mb-3 font-normal text-white text-ellipsis"><%= group.description %></p>
  <p class="mb-3 font-normal text-white">5人のメンバーが参加しています。</p>
  <% if group.users.include?(current_user) %>
    <%= link_to group_path(group.id), class: "inline-flex items-center text-blue-600 hover:underline" do %>
      チームを見る
      <svg class="ml-2 w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M11 3a1 1 0 100 2h2.586l-6.293 6.293a1 1 0 101.414 1.414L15 6.414V9a1 1 0 102 0V4a1 1 0 00-1-1h-5z"></path><path d="M5 5a2 2 0 00-2 2v8a2 2 0 002 2h8a2 2 0 002-2v-3a1 1 0 10-2 0v3H5V7h3a1 1 0 000-2H5z"></path></svg>
    <% end %>
  <% else %>
    <%= link_to group_path(group.id), class: "inline-flex items-center text-blue-600 hover:underline" do %>
      チームに参加する....
      <svg class="ml-2 w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M11 3a1 1 0 100 2h2.586l-6.293 6.293a1 1 0 101.414 1.414L15 6.414V9a1 1 0 102 0V4a1 1 0 00-1-1h-5z"></path><path d="M5 5a2 2 0 00-2 2v8a2 2 0 002 2h8a2 2 0 002-2v-3a1 1 0 10-2 0v3H5V7h3a1 1 0 000-2H5z"></path></svg>
    <% end %>
  <% end %>
</div>

app/views/groups/_payment_table.html.erb
<table class="text-sm w-full text-left text-gray-500 container mx-auto">
  <thead class="text-xs font-bold text-gray-700 uppercase bg-blue-400">
    <tr>
      <th scope="col" class="py-3 px-6">
        支払い項目
      </th>
      <th scope="col" class="py-3 px-6">
        支払い者
      </th>
      <th scope="col" class="py-3 px-6">
        金額
      </th>
    </tr>
  </thead>
    <tbody>
      <% 5.times do %>
        <tr class="bg-blue-300">
            <th scope="row" class="py-4 px-6 font-bold text-gray-900 whitespace-nowrap dark:text-white">
                Apple MacBook Pro 17"
            </th>
            <td class="py-4 px-6">
                John
            </td>
            <td class="py-4 px-6">
                $2999
            </td>
        </tr>
      <% end %>
    </tbody>
</table>

app/views/groups/index.html.erb
<div class='w-screen min-h-screen justify-center items-center'>
  <div class='w-full h-[20vh] text-center pt-10 text-5xl text-blue-600 font-thin'>
    Teams
    <span class='hover:cursor-cell'>
      <%= link_to create_group_path do %>
        <span class="material-icons text-3xl ml-10 animate-ping duration-300">group_add</span>
      <% end %>
    </span>
  </div>
  <div class='w-full h-screen my-10'>
    <div class='container mx-auto'>
      <div class='grid grid-cols-3 gap-4'>
        <% @groups.each do |group| %>
          <%= render 'groups/group_card', group: group %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="h-[87vh] w-screen flex justify-center items-center pb-[30px]">
  <%= form_with model: @group, url: groups_path, method: :post, class: "w-full max-w-sm", local: true do |f| %>
  <p class='text-center text-blue-500 font-bold text-4xl mb-10 italic'>New Group</p>
    <div class="md:flex md:items-center mb-6">
      <div class="md:w-1/3">
        <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-full-name">
          group Name
        </label>
      </div>
      <div class="md:w-2/3">
        <%= f.text_field :name, class: "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500", placeholder: "name" %>
      </div>
    </div>
    <div class="md:flex md:items-center mb-6">
      <div class="md:w-1/3">
        <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-password">
          Description
        </label>
      </div>
      <div class="md:w-2/3">
        <%= f.text_field :description, class: "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500", placeholder: 'put the group description' %>
      </div>
    </div>
    <div class="md:flex md:items-center">
      <div class="md:w-1/3"></div>
      <div class="md:w-2/3">
        <%= f.submit 'create', class: "shadow bg-blue-500 hover:bg-blue-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded" %>
      </div>
    </div>
  <% end %>
</div>

app/views/groups/show.html.erb
<div class='w-screen min-h-screen justify-center items-center'>
  <div class='w-full h-[20vh] text-center pt-10 text-5xl text-blue-600 font-thin'>
    Team
    <span class='hover:cursor-cell'>
      <%= link_to groups_path do %>
        <span class="material-icons text-3xl ml-10 animate-ping duration-300">add_shopping_cart</span>
      <% end %>
    </span>
  </div>
  <div class='w-full h-screen my-10'>
    <div class='rounded-md'>
      <%= render 'groups/payment_table' %>
    </div>
  </div>
</div>

app/views/homes/_serviseName.html.erb
<span class='font-bold'>
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="inline-block w-6 h-6 text-sky-400">
    <path stroke-linecap="round" stroke-linejoin="round" d="M9 7.5l3 4.5m0 0l3-4.5M12 12v5.25M15 12H9m6 3H9m12-3a9 9 0 11-18 0 9 9 0 0118 0z" />
  </svg>
  Wari
  <span class='text-blue-400'>pal</span>
</span>

app/views/homes/docs.html.erb
<div class="w-screen h-[87vh] flex justify-center items-center bg-gradient-to-r from-blue-100 via-blue-300 to-blue-500 rounded-tl-full">
  <div>
    <div class='p-5'>
      <p class="pl-[40px] text-3xl text-white" style="font-family: 'Merriweather', serif;">tutorial</p>
      <p class='font-thin text-xl pt-4 pl-[40px]'>wari palの使い方の一覧を載せた動画を作成しておりますのでご参照ください</p>
    </div>
    <div class='pl-[50px]'>
      <iframe width="560" height="315" src="https://www.youtube.com/embed/xf9eLhExFZM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div>
  <div class='w-full flex'>
    <%# top content image %>
    <div class='object-contain h-[520px] w-[520px]'>
      <%= image_tag 'top.png' %>
    </div>

    <%# top content title %>
    <div class='px-3 py-[30px]'>
      <p class='font-thin text-5xl text-black pt-10'>
        ようこそ
        <%= render 'serviseName' %>へ！
      </p>
      <%# top content %>
      <p class='py-10 font-thin text-center tracking-wide leading-6'>
        <span class=''>
        <br />
        このサイトでは、旅行先の支払いを登録しておくことで
        <br />
        面倒な精算を一度に済ませることができます。
      </p>

      <%# sign_in_page && teams page %>
      <%= link_to docs_path, class: 'w-full flex justify-center pt-[20px]' do %>
        <span class='btn px-4 border border-blue-300 py-2 text-white rounded-md text-blue-300'>Start</span>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="w-full h-auto text-center">
  <span class="block text-sm text-gray-500 dark:text-gray-400">© 2022 <a href="https://flowbite.com" target="_blank" class="hover:underline">Flowbite™</a>. All Rights Reserved.
</div>

app/views/layouts/_header.html.erb
<nav class="flex items-center justify-between flex-wrap p-6">
  <%# logo display %>
  <%= link_to root_path, class: 'hover:cursor' do %>
    <div class="flex items-center flex-no-shrink text-cream mr-8 ml-10">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 text-sky-400">
        <path stroke-linecap="round" stroke-linejoin="round" d="M9 7.5l3 4.5m0 0l3-4.5M12 12v5.25M15 12H9m6 3H9m12-3a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
      <span class="font-semibold text-xl tracking-tight">Wari <span class='text-blue-600'>Pal</span></span>
    </div>
  <% end %>
  <%# link menu display%>
  <div class="block lg:hidden">
    <button class="flex items-center px-3 py-2 border rounded text-teal-lighter border-teal-light hover:text-white hover:border-white">
      <svg class="h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
        <title>Menu</title>
        <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/>
      </svg>
    </button>
  </div>
  <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
    <div class="text-sm lg:flex-grow text-gray-400">
      <%= link_to docs_path, class: "block mt-4 lg:inline-block lg:mt-0 text-teal-lighter hover:text-gray-800 mr-4" do %>
        Docs
      <% end %>
      <% if current_user %>
        <%= link_to mypage_path(current_user.id), class: "block mt-4 lg:inline-block lg:mt-0 text-teal-lighter hover:text-gray-800 mr-4" do %>
          Mypage
        <% end %>
        <%= link_to users_path, class: "block mt-4 lg:inline-block lg:mt-0 text-teal-lighter hover:text-gray-800 mr-4" do %>
          Users
        <% end %>
        <%= link_to groups_path, class: "block mt-4 lg:inline-block lg:mt-0 text-teal-lighter hover:text-gray-800 mr-4" do %>
          Team
        <% end %>
      <% end %>
    </div>
    <div class='mr-8'>
      <% if current_user %>
        <span class="inline-block text-sm px-4 py-2 leading-none border rounded text-blue-400 border-blue-400 hover:border-transparent hover:bg-blue-400 hover:text-white mt-4 lg:mt-0">
          <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
        </span>
      <% else %>
        <span class="inline-block text-sm px-4 py-2 leading-none border rounded text-blue-400 border-blue-400 hover:border-transparent hover:bg-blue-400 hover:text-white mt-4 lg:mt-0">
          <%= link_to 'Sign in', new_user_session_path %>
        </span>
        <span class="inline-block text-sm px-4 py-2 leading-none border rounded text-blue-400 border-blue-400 hover:border-transparent hover:bg-blue-400 hover:text-white mt-4 lg:mt-0">
          <%= link_to 'Sign up', new_user_registration_path %>
        </span>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ServerLesson</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%# tailwind css CDN import %>
    <script src="https://cdn.tailwindcss.com"></script>

    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,400;1,300&family=Noto+Serif+JP:wght@500&family=Playfair+Display:wght@700&display=swap" rel="stylesheet">
  </head>

  <body class="w-full min-h-screen">
    <%# header %>
    <header>
      <%= render 'layouts/header' %>
    </header>

    <%# content %>
    <div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_users_card.html.erb
<div class="p-6 max-w-sm bg-white rounded-lg shadow-md bg-blue-400">
  <span class="material-icons text-white">
    person_pin_circle
  </span>
  <a href="#">
    <h5 class="mb-2 text-2xl text-center font-semibold tracking-tight text-gray-900 dark:text-white">
      <span class='shadow-md shadow-transparent'><%= user.name %></span>
    </h5>
  </a>
  <p class="mb-3 font-normal text-white"><%= user.description %></p>
</div>

app/views/users/index.html.erb
<div class='w-screen min-h-screen justify-center items-center'>
  <div class='w-full h-[20vh] text-center pt-10 text-5xl text-blue-600 font-thin'>
    Members<span class="material-icons text-5xl">portrait</span>
  </div>
  <div class='w-full h-screen my-10'>
    <div class='container mx-auto'>
      <div class='grid grid-cols-3 gap-4'>
        <% @users.each do |user| %>
          <%= render 'users/users_card', user:user %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class='w-full max-h-screen'>
  <div class='w-full h-[87vh] bg-gradient-to-r from-blue-100 via-blue-300 to-blue-500 rounded-t-[500px]'>
    <div class='ml-[600px] py-[50px]'>
      <div class="max-w-3xl mx-auto">
        <div class="max-w-md bg-blue-500 rounded-lg hover:scale-125 duration-500 shadow-lg">
          <div class="flex py-10 flex-col items-center pb-10">
            <img class="mb-3 w-24 h-24 rounded-full shadow-lg" src="https://flowbite.com/docs/images/people/profile-picture-3.jpg" alt="Bonnie image">
            <h3 class="mb-1 text-xl font-medium text-gray-900 dark:text-white"><%= @user.name %></h3>
            <span class="text-sm text-white">Visual Designer</span>
            <div class="mt-4 space-x-3 lg:mt-6 text-white inline-flex">
              <p class="text-md text-white m-2"><span class="material-icons mr-2">groups_3</span><%= @user.groups.count %> teams</p>
              <p class="text-md text-white m-2"><span class="material-icons pt-1 mr-2 text-ellipsis">description</span><%= @user.description %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= image_tag 'mypage.png', class: 'w-[450px] h-[500px] absolute bottom-0 left-0' %>
</div>